### ISSUE TITLE
Help with bitbucket pipeline usage

### ISSUE THREAD

**Issue by tomas-rokos** [instrumentisto/dart-content-shell-docker-image#5]
Hello,
I would like to ask for help with this docker image. I am using angular dart with embedded testing solution. I would like to use it also automated in bitckucket pipelines functionality, which is based on Docker images. I setup this repository https://bitbucket.org/tomas-rokos/ang_pipelines and used your docker image. PUB GET worked out fine but running tests failed on not able to find content shell.

Do you have some fast hint? I don't want to waste your time, but I am not familiar with docker too much to be able to debug it.

Thank you,
Tomáš

sample result: https://bitbucket.org/tomas-rokos/ang_pipelines/addon/pipelines/home#!/results/%7B236ee072-b8e4-4c8b-8fba-8b2e36f9724a%7D

**Comment by tomas-rokos** [comment]
I just found that the content_shell could be found and loaded, but ends with:
[29:29:0705/095033:23454838461:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.

So I will need to find a way how to run content_shell without SUID. 
Closing as this is not related to the docker file at all

**Comment by tyranron** [comment]
@tomas-rokos hi!

You should prepend your command which uses `content_shell` with `xvfb-run`.

This is done in `Dockerfile` [implicitly](https://github.com/instrumentisto/dart-content-shell-docker-image/blob/40f6c6399935d7a57ec52a201d1848a4ac61ca46/Dockerfile#L62). But you are using the image as build environment, not a command-runner one, so implicit command just doesn't fire for your `content_shell` command. And running `content_shell` without `Xvfb` is not possible.

Try in your pipeline spec following command:
```bash
xvfb-run -s '-screen 0 1024x768x24' pub run test --platform=content-shell
```
This should work.

As to `Running without the SUID ` error. We had our investigation over it and the result is that this is a warning, not a real error that breaks stuff. The same is with `Xlib:  extension "RANDR" missing on display ":99".`, `glxQueryVersion failed` and `GLSurfaceGLX::InitializeOneOff failed.` errors.

Be aware of using `-e` flag for `xvfb-run`. It somehow breaks everything and makes execution stuck. No desire to dive into details, so with just omit that flag.

**Comment by tomas-rokos** [comment]
Outstanding. It works. Thank you very much. You made my day.
